import { Layout } from "@components/Layout";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const data = [
  {
    id: 1,
    img: "/assets/svg/palmeras.svg",
    title: "Beaches",
  },
  {
    id: 2,
    img: "/assets/svg/cactus.svg",
    title: "Deserts",
  },
  {
    id: 3,
    img: "/assets/svg/montaña.svg",
    title: "Mountains",
  },
  {
    id: 4,
    img: "/assets/svg/totte_pizza.svg",
    title: "Iconic Cities",
  },
  {
    id: 5,
    img: "/assets/svg/houseboat.svg",
    title: "Houseboats",
  },
  {
    id: 6,
    img: "/assets/svg/vereda.svg",
    title: "Countryside",
  },
  {
    id: 7,
    img: "/assets/svg/camping.svg",
    title: "Camping",
  },
  {
    id: 8,
    img: "/assets/svg/castle.svg",
    title: "Castles",
  },
  {
    id: 9,
    img: "/assets/svg/skiing.svg",
    title: "Skiing",
  },
  {
    id: 10,
    img: "/assets/svg/palmera.svg",
    title: "tropical",
  },
];

const top_vacation = [
  {
    id: 1,
    img: "/assets/images/indenosia.png",
    city: "Bali",
    country: "Indonesia",
  },
  {
    id: 2,
    img: "/assets/images/ireland.png",
    city: "Kerry",
    country: "Ireland",
  },
  {
    id: 3,
    img: "/assets/images/australia.png",
    city: "Sydney",
    country: "Australia",
  },
  {
    id: 4,
    img: "/assets/images/france.png",
    city: "Paris",
    country: "France",
  },
];

const offers = [
  {
    id: 1,
    img: "/assets/images/offers_img1.png",
    company: "Domestic Flights",
    description: "Huge savings on flight with trxl.",
    comment: "Book domestic flights starting @just 1459",
    link: "#",
  },
  {
    id: 2,
    img: "/assets/images/offers_img2.png",
    company: "International Hotels",
    description: "Enjoy upto 20% off on International Hotels",
    comment: "Make the most of this deal on your first booking with trxvl.",
    link: "#",
  },
  {
    id: 3,
    img: "/assets/images/offers_img1.png",
    company: "Domestic Flights",
    description: "Huge savings on flight with trxl.",
    comment: "Book domestic flights starting @just 1459",
    link: "#",
  },
];

const browse_type = [
  {
    id: 1,
    name: "Hotels",
    img: "/assets/images/hotels.png",
    link: "#",
  },
  {
    id: 2,
    name: "Apartments",
    img: "/assets/images/apartments.png",
    link: "#",
  },
  {
    id: 3,
    name: "Resorts",
    img: "/assets/images/resorts.png",
    link: "#",
  },
  {
    id: 4,
    name: "Villas",
    img: "/assets/images/villas.png",
    link: "#",
  },
];

const other_trip = [
  {
    id: 1,
    title: "India",
    coment: "Travel community",
    travelers: 155073,
    img: "/assets/images/other_img1.png",
  },
  {
    id: 2,
    title: "Travel Talk",
    coment: "Travel community",
    travelers: 155073,
    img: "/assets/images/other_img2.png",
  },
  {
    id: 3,
    title: "Beach",
    coment: "Travel community",
    travelers: 155073,
    img: "/assets/images/other_img3.png",
  },
  {
    id: 4,
    title: "Mountains",
    coment: "Travel community",
    travelers: 155073,
    img: "/assets/images/other_img4.png",
  },
];

export const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {/* Top Vacation destination */}
        <div className="relative w-full h-[270px]">
          <div className="z-0 absolute flex flex-col gap-8 w-auto">
            <div className="z-0 lg:text-white font-semibold text-3xl w-auto">
              Top Vacation Destinations
            </div>
            <div className="flex gap-5">
              {top_vacation.map(({ id, img, city, country }) => {
                return (
                  <div
                    key={id}
                    className="relative w-[310px] h-[200px] cursor-pointer transition-all duration-500 hover:scale-105"
                  >
                    <Image
                      src={img}
                      alt="australia"
                      width={310}
                      height={200}
                      className=" rounded-md w-[310px] h-[200px]"
                    />
                    <div className="absolute bottom-7 left-6">
                      {city}, {country}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Offers */}
        <div className="z-0 relative flex flex-col gap-8 ">
          <div className=" font-semibold text-black text-3xl w-auto">
            Offers
          </div>
          <div className="flex gap-5">
            {offers.map(({ id, company, description, comment, img }) => (
              <div
                className="flex gap-6 p-6 w-[680px]  text-black rounded-2xl shadow-md cursor-pointer transition-all duration-500 
                    hover:scale-[1.005]"
                key={id}
              >
                <div className="w-[310px] h-[210px] overflow-hidden rounded-lg">
                  <Image src={img} alt="" width={310} height={210} />
                </div>
                <div className="flex flex-col  justify-between ">
                  <div>
                    <div className="text-base">{company}</div>
                    <div className="text-2xl font-semibold">{description}</div>
                    <div className="text-base">{comment}</div>
                  </div>

                  <button
                    className="
                              bg-[#2659C3] p-4   w-[140px] 
                              text-white text-base rounded-full
                                shadow-md
                                cursor-pointer transition-all duration-500 
                                hover:scale-105 hover:shadow-lg
                                "
                  >
                    Book now
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Browse property */}
        <div className="z-0 flex flex-col  gap-10 mb-4">
          <div className="font-semibold text-3xl text-black">
            Browse by property type
          </div>
          <div className="flex gap-[55px]">
            {browse_type.map(({ id, name, img }) => (
              <div
                key={id}
                className="relative w-[310px] h-[200px] cursor-pointer transition-all duration-500 hover:scale-105"
              >
                <Image
                  src={img}
                  alt="australia"
                  width={310}
                  height={200}
                  className=" rounded-md w-[310px] h-[200px]"
                />
                <div className="absolute bottom-7 left-6">{name}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Plan trip */}
        <div className="flex flex-col gap-6 p-20 h-[400px] w-full bg-hero-map-trip rounded-3xl">
          <p className="w-[640px] text-[56px] leading-[64.39px] font-semibold">
            Plan your trip with travel expert
          </p>
          <p>Our professional advisors can craft your perfect itinerary</p>
        </div>

        {/* Connect with other travelers */}
        <div className="text-black">
          <p className=" font-semibold">
            Connect with travelers in our community
          </p>
          <div className="flex gap-6 ">
            {other_trip.map(({ id, title, coment, travelers, img }) => (
              <div
                key={id}
                className="p-4 rounded-2xl shadow-md transition-all hover:scale-105 cursor-pointer "
              >
                <div className="w-[310px] h-[200px] rounded-lg ">
                  <Image
                    className="rounded-lg"
                    src={img}
                    alt=""
                    width={310}
                    height={200}
                  />
                </div>
                <p className="text-2xl">{title}</p>
                <p className="text-base">{coment}</p>
                <p className="text-base">{travelers} travelers</p>
              </div>
            ))}
          </div>
        </div>
        {/* ultima parte home */}
        <div className="relative -left-[125px] top-[125px] grid grid-cols-[270px_1fr] gap-20 pt-[70px] px-[130px] h-[540px] bg-mountains-blue ">
          {/* Lateral izquierdo */}
          <div className="w-[260px] h-[580px]">
            <Image
              src="/assets/images/mockup-app.png"
              alt=""
              width={260}
              height={580}
            />
          </div>
          {/* Lateral derecho */}
          <div className="text-white">
            <p className="text-5xl font-semibold ">
              Your all-in-one travel app.
            </p>
            <p className="text-2xl mt-6 mb-10 w-[780px]">
              Book flights, hotels, trains & rental cars anywhewre in the word
              in just seconds. Get real-time flight updates, travel info,
              exclusive details, and 30% more Trip Coins on the app!
            </p>
            {/* Parte baja */}
            <div className="flex justify-between w">
              <div className="flex flex-col gap-4">
                <div className=" flex items-center gap-6 mb-4 text-xl">
                  <p className="bg-gris-trasparent py-2 px-4 rounded-2xl cursor-pointer">
                    Mobile
                  </p>
                  <p className="cursor pinter"> Email</p>
                </div>
                <p className="text-sm">
                  Enter your phone number to recive a text with a link to
                  download the app.
                </p>
                <div className="relative w-[460px]">
                  <input
                    type="number"
                    placeholder="+91 Movile number"
                    className="px-4 w-full h-[60px] bg-gris-trasparent placeholder:text-white text-base rounded-2xl"
                  />
                  <button className="absolute top-[6px] right-4 py-3 px-16 bg-white text-base text-[#2659C3] font-semibold rounded-full cursor-pointer">
                    Search
                  </button>
                </div>
              </div>
              <div className="relative flex justify-center items-center w-1 after:content-[''] after:absolute after:top-[0px] after:w-[1px] after:h-[70px] after:text-center  after:bg-white before:content-[''] before:absolute before:-bottom-[10px] before:w-[1px] before:h-[70px] before:text-center  before:bg-white">
                or
              </div>
              <div className="flex flex-col justify-center items-center gap-4">
                <Image
                  src="/assets/images/download-app-google.png"
                  alt="Download Google play"
                  width={200}
                  height={60}
                />
                <Image
                  src="/assets/images/download-app-store.png"
                  alt="download app store"
                  width={200}
                  height={60}
                />
              </div>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Home;
