import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const data = [
  {
    id: 1,
    img: "/assets/svg/palmeras.svg",
    title: "Beaches",
  },
  {
    id: 2,
    img: "/assets/svg/cactus.svg",
    title: "Deserts",
  },
  {
    id: 3,
    img: "/assets/svg/montaña.svg",
    title: "Mountains",
  },
  {
    id: 4,
    img: "/assets/svg/totte_pizza.svg",
    title: "Iconic Cities",
  },
  {
    id: 5,
    img: "/assets/svg/houseboat.svg",
    title: "Houseboats",
  },
  {
    id: 6,
    img: "/assets/svg/vereda.svg",
    title: "Countryside",
  },
  {
    id: 7,
    img: "/assets/svg/camping.svg",
    title: "Camping",
  },
  {
    id: 8,
    img: "/assets/svg/castle.svg",
    title: "Castles",
  },
  {
    id: 9,
    img: "/assets/svg/skiing.svg",
    title: "Skiing",
  },
  {
    id: 10,
    img: "/assets/svg/palmera.svg",
    title: "tropical",
  },
];

const Home: NextPage = () => {
  return (
    <div className="relative text-white flex justify-center my-20 font-">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" relative w-[1366px]">
        <header className="absolute flex justify-between items-center px-10 w-full py-6 ">
          <div className="text-3xl font-bold">trxvl.</div>
          <nav className="flex gap-5 items-center mr-10 text-lg font-light ">
            <div className="border-blue-100">Home</div>
            <div>Stays</div>
            <div>Flights</div>
            <div>Packages</div>
            <div>Sing Up</div>
          </nav>
        </header>

        <main className="">
          <section
            className="
                  box-content
                  flex flex-col justify-start items-start
                  gap-10
                  h-screen  p-[120px]
                  bg-hero-pattern bg-contain bg-no-repeat
                  "
          >
            {/* <Image
            src="/assets/images/image1.png"
            alt=""
            width="100%"
            height="100%"
            layout="fill"
          /> */}
            <div className="w-[580px] mt-1 text-7xl font-bold ">
              The Whole world awaits.
            </div>
            <form
              action=""
              className="
            flex  justify-between items-center px-6 
            w-full
            h-[60px] bg-gris-trasparent
            rounded-2xl"
            >
              <div className="flex items-center ">
                <Image
                  src="/assets/svg/search.svg"
                  alt=""
                  width={32}
                  height={32}
                />
                <input
                  type="text"
                  className="px-2 w-80 h-[44px] bg-transparent text-lg placeholder:text-white"
                  placeholder="search destinations, hotels"
                />
              </div>
              <div className="flex gap-8 items-center">
                <div className="flex items-center ">
                  <Image
                    src="/assets/svg/akar-icons_calendar.svg"
                    alt=""
                    width={32}
                    height={32}
                  />
                  <input
                    type="text"
                    className="px-2 w-40 h-[44px] bg-transparent text-lg placeholder:text-white"
                    placeholder="Check in"
                  />
                </div>
                <div className="flex items-center ">
                  <Image
                    src="/assets/svg/akar-icons_calendar.svg"
                    alt=""
                    width={32}
                    height={32}
                  />
                  <input
                    type="text"
                    className="px-2 w-40 h-[44px] bg-transparent text-lg placeholder:text-white"
                    placeholder="check out"
                  />
                </div>
                <div className="flex items-center ">
                  <Image
                    src="/assets/svg/fontisto_male.svg"
                    alt=""
                    width={32}
                    height={32}
                  />
                  <input
                    type="text"
                    className="px-2 w-40 h-[44px] bg-transparent text-lg placeholder:text-white"
                    placeholder="1 room, 2 adults"
                  />
                </div>
                <button
                  type="submit"
                  className="
                  flex justify-center
                  items-center px-8 
                  py-5 h-8 bg-white 
                  text-blue-600 text-base rounded-3xl"
                >
                  Search
                </button>
              </div>
            </form>
            <div className="flex flex-col  gap-10">
              <div className="font-semibold text-4xl">Top categories</div>
              <div className="flex gap-14">
                {data.map(({ id, img, title }) => {
                  return (
                    <div key={id} className="flex flex-col items-center">
                      <Image src={img} alt="" width={50} height={50} />
                      <div className="text-base font-light">{title}</div>
                    </div>
                  );
                })}
              </div>
            </div>
          </section>
        </main>
      </div>
    </div>
  );
};

export default Home;
